### PR TITLE
Enh/celery

### PR DESCRIPTION
**Pull request by infocortex**
Celery with redis config and daemonization.

### CODE REVIEW

**Comment by vsoch** [comment]
I think my configuration for vagrant may be different, leading to this error:

      ==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
      [sudo] password for vanessa: 
      nfsd running
      exportfs: /etc/exports: 7: bad anonuid "anonuid=root"

      ==> default: Mounting NFS shared folders...
      The following SSH command responded with a non-zero exit status.
      Vagrant assumes that this means the command failed!

      mount -o 'vers=3,udp' 192.168.33.1:'/home/vanessa/Desktop/nv_env/neurovault_puppet' /etc/puppet/modules/neurovault

      Stdout from the command:



      Stderr from the command:

      stdin: is not a tty
      mount.nfs: access denied by server while mounting 192.168.33.1:/home/vanessa/Desktop/nv_env/neurovault_puppet

The machine loads, but the mount to 192.168.33.1 isn't active.  The error is talking about this line:

      config.vm.synced_folder "neurovault_puppet", "/etc/puppet/modules/neurovault", type:"nfs", create:true, map_uid: 'root', map_gid: 'wheel'

for my installation that works, I don't actually specify root, I do:

      config.vm.synced_folder "neurovault_puppet", "/etc/puppet/modules/neurovault", type:"nfs", create:true, map_uid: '1000', map_gid: '10000'      

I think maybe the user ID can't be hard coded? for example, take a look at the user ids on my machine:

     $ id vanessa
      uid=1000(vanessa) gid=1000(vanessa) groups=1000(vanessa),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),108(lpadmin),124(sambashare)
      $ id root
      uid=0(root) gid=0(root) groups=0(root)

I'm super sleepy and don't have enough awakeness left to debug this properly - will give a look again tomorrow morning!

**Comment by vsoch** [comment]
boom! I completely broke my NeuroVault vm but I just figured out how to do this. The issue is that when you try to mount and get an error, the vagrant stores it's attempt in /etc/exportfs and will retry the wonky one every time (always leading to an error). For example:

      sudo vim /etc/exports

I see

      # VAGRANT-BEGIN: 1000 9bfb8ce1-3a88-4173-a67e-7b70eff3e94e
      "/home/vanessa/Packages/vagrant/neurovault/neurovault_puppet" 192.168.33.10(rw,no_subtree_check,all_squash,anonuid=1000,anongid=wheel,fsid=399783149)
      "/home/vanessa/Packages/vagrant/neurovault/nv_env" 192.168.33.10(rw,no_subtree_check,all_squash,anonuid=1000,anongid=wheel,fsid=1116967821)
      "/home/vanessa/Packages/vagrant/neurovault/image_data" 192.168.33.10(rw,no_subtree_check,all_squash,anonuid=1000,anongid=wheel,fsid=3802941516)

I don't really understand this "root" and "wheel" business, but when I set it to ids for group and my user that actually exist, the mount works.  So I just needed to delete all these lines So here is my workflow for resetting the machine to test yours:

      # delete old cached corrupt machine
      rm -rf .vagrant/
      
      # get your branch, first I needed to save my specific config to a different one
      git checkout -b vanessa
      git commit -a
      git checkout -b enh/celery origin/enh/celery
      git merge vanessa

Since my custom config is in the Vagrantfile copied outside of the directory, the merge shouldn't be an issue! (and it looks like there aren't substantial changes to the Vagrantfile itself). Now that I am sure the corrupt /etc/exports and cached machine is dead, I can try to recreate the box:
      
      vagrant up

And now all the new stuffs are flying by on my screen with your new config to test! I'll hopefully be able to give some feedback soon. And I hope this fixes the now not working NeuroVault vm! I have much things I want to do this weekend  :O)

**Comment by vsoch** [comment]
The machine was generated without error. Then:

      vagrant ssh -- -Y
      sudo service uwsgi restart

I got an nginx error.

      sudo apt-get install vim
      vim /var/log/nginx/localhost.error.log
      2015/02/06 09:36:05 [crit] 4963#0: *1 connect() to unix:/tmp/neurovault.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.33.1, server: localhost, request: "GET /compare/1/2 HTTP/1.1", upstream: "uwsgi://unix:/tmp/neurovault.sock:", host: "192.168.33.10"

If anyone has any ideas about how to debug this, would be appreciated! For the time being I can run the server manually:

     source /opt/nv_env/bin/activate
     python /opt/nv_env/NeuroVault/manage.py runserver

Then I open another terminal (enabling graphics forwarding)

      vagrant ssh -- -Y
      sudo apt-get install firefox
      firefox

And I see NeuroVault at localhost:8000

Now to test puppet! I first restarted the tasks, just in case:

      sudo service neurovault-tasks restart

I first uploaded some images, the folder upload does not work on firefox ubuntu linux, it seems. The zip did work, however there is a papaya error that says "not a gzip file!" (this is another issue). I looked to see if the brain images were calculated - they were not.

      celery status
      ....[lots of errors here]
      socket.error: [Errno 111] Connection refused

Redis is working

      redis-cli ping
      PONG

Now to try starting celery manually:

      /opt/nv_env/NeuroVault/manage.py celery worker -A neurovault.celery -l info -E --autoreload

I then uploaded a new set of images, and got a bunch of nilearn errors. As @infocortex  suggested, I am going to reinstall nilearn

      sudo pip uninstall nilearn
      sudo pip install nilearn
      sudo service uwsgi restart
      sudo service neurovault-tasks restart

I then deleted the collection and tried again (note that deleting the collection doesn't actually delete the images, although the interface told me it did, this could potentially lead to error?  Here is the error that celery is spitting out:

      Task neurovault.apps.statmaps.tasks.save_voxelwise_pearson_similarity[b4bc9dd0-a37c-4352-be65-74fe613c78b1] raised unexpected: DoesNotExist('Similarity matching query does not exist.',)

Oh yes, I need to add the Similarity metric manually! We should probably add this to the puppet config? Running the script manually didn't work, so I did this in the shell:

      manage.py shell
      [copied code from scripts/add_pearson_similarity_metric

What happened to update_voxelwise_pearson_similarity? it's no longer in tasks.py. Maybe I missed this? I removed its import from the script so I can push with the next update. Next I tried restarting celery, and re-uploading images. And ho! It's working now! So adding the metric to neurovault_puppet - is this something we want to do?  So now I can confirm that the similarity calculations are working. But the brainglass image generation is not. The error is:

      [2015-02-06 19:23:36,499: ERROR/MainProcess] Task neurovault.apps.statmaps.tasks.generate_glassbrain_image[1244a32e-12c3-46de-8db9-c3d698b67975] raised unexpected: TclError('no display name and no $DISPLAY environment variable',)

One note - when the similarity calculations worked and the glass brain ones didn't, the similarity search still returned, just without the images. It seems arduous to implement a check for the images every time - but we could get a bug if an image is not generated but the score is. What do you guys think?

Now to debug the glass brain image generation - I remembered that I had started this terminal with `vagrant ssh` without the `-- -Y` so I restarted with display, and restarted celery, and did the process again. Ho! Now the glass brain generation is working.  I am (almost) where i left off before corrupting my old vm, however the two points of concern:

 - nginx is not working
 - the celery daemon still needs a manual start

I hope this was helpful - I do need some help to debug the two things above, because developing is a lot slower with manual firefox :stuck_out_tongue: When the above two things are worked out, here is a summary of the smaller issues for discussion:

 - not using root and wheel?
 - adding similarity metric generation to puppet?
 - some check for glass brain images?
 - we are no longer needing update_voxelwise_pearson_similarity?
 - papaya viewer not working when running locally (maybe fixed if nginx works)
 - also, in this browser, the buttons are > the width of the window:

picture

That's it for now. I think I'm at a place I can keep doing dev work, although the workflow is a little arduous! Let me know if you have thoughts for the nginx issue, and the celery daemon.

**Comment by infocortex** [comment]
Hi, I think you are having some permissions problems that are causing most of the trouble here.  If you are using NFS, I'd also use BindFS to map the user id's between your system and puppet.  Or just use the default rsync configuration.  Here's an example for NFS and BindFS:

```
config.vm.synced_folder "neurovault_puppet", "/mnt/etc/puppet/modules/neurovault", nfs:true, create:true
config.bindfs.bind_folder "/mnt/etc/puppet/modules/neurovault", "/etc/puppet/modules/neurovault"

config.vm.synced_folder "nv_env", "/mnt/opt/nv_env", nfs:true, create:true
config.bindfs.bind_folder "/mnt/opt/nv_env", "/opt/nv_env"

config.vm.synced_folder "image_data", "/mnt/opt/image_data", nfs:true, create:true
config.bindfs.bind_folder "/mnt/opt/image_data", "/opt/image_data"

#  Mount point of pycortex datastore
config.vm.synced_folder "pycortex_data", "/mnt/opt/pycortex_data", nfs:true, create:true
config.bindfs.bind_folder "/mnt/opt/pycortex_data", "/opt/pycortex_data"
``

In general I'd advise a fresh vagrant instance.  Also, I have no idea with is going on with X forwarding, I wouldn't advise working that way, just access the VM from your native browser on your system, its much easier imo.

> not using root and wheel?
Check out BindFS config for Vagrant, it should sort out the permissions problem.

adding similarity metric generation to puppet?
some check for glass brain images?
we are no longer needing update_voxelwise_pearson_similarity?
papaya viewer not working when running locally (maybe fixed if nginx works)
also, in this browser, the buttons are > the width of the window:

**Comment by infocortex** [comment]
>  (note that deleting the collection doesn't actually delete the images, although the interface told me it did, this could potentially lead to error?

Yep, its default Django behavior to not actually delete things from the filesystem when DB objects are deleted.  It shouldn't break anything, but I've considered added a post_delete event that actually cleans the filesystem.

```
2015/02/06 09:36:05 [crit] 4963#0: *1 connect() to unix:/tmp/neurovault.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.33.1, server: localhost, request: "GET /compare/1/2 HTTP/1.1", upstream: "uwsgi://unix:/tmp/neurovault.sock:", host: "192.168.33.10"
```

Hmm, I've gotten this a couple times- you can manually `rm -rf  /tmp/neurovault.sock` and restart nginx, and all should be ok.

**Comment by infocortex** [comment]
```
  [2015-02-06 19:23:36,499: ERROR/MainProcess] Task neurovault.apps.statmaps.tasks.generate_glassbrain_image[1244a32e-12c3-46de-8db9-c3d698b67975] raised unexpected: TclError('no display name and no $DISPLAY environment variable',)
```

I got this too, its an error with matplotlib looking for an X server, but when I updated matplotlib it went away for me.  Maybe still a problem with a fresh build?  Here's is a workaround for `settings.py` or `local_settings.py`, that forces matplotlib to render without X:

```python
import matplotlib as mpl
mpl.use('Agg')
```

**Comment by vsoch** [comment]
The port forwarding was working for me before without bindfs, but it sounds like I should get this setup. For the example you provided, where exactly does that go?  If using bindfs is the only way for it to work with "root" and "wheel" is there documentation we can provide to get it set up?

**Comment by vsoch** [comment]
Oh I see, I do:

     vagrant plugin install vagrant-bindfs

And then add that to the Vagrantfile. Let me try that.

**Comment by vsoch** [comment]
That didn't fix anything, unfortunately. I'm still getting a nginx error, and the log says:

     2015/02/06 15:10:24 [crit] 5454#0: *1 connect() to unix:/tmp/neurovault.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.33.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/tmp/neurovault.sock:", host: "192.168.33.10"

Any ideas? This is really discouraging.

**Comment by infocortex** [comment]
Bummer,

Did you try manually deleting `neurovault.sock`?

Are you using a fully fresh vagrant instance, in a new directory, and/or destroying the existing VM for a fresh start? Otherwise the file system will still hang around (its not in the .vagrant directory iirc)

```
vagrant destroy
rm -rf .vagrant
vagrant up
```

Are you using `vagrant` as the `$system_user` in the Puppet config?  (Shouldn't be necessary, but it will simplify the permissions...)

Failing that, send over your `Vagrantfile` and `confs/nvault.pp` and I'll try to see whats amiss.  

Or, start completely fresh and follow the `INSTALL_DEVSERVER.md` exactly with no changes if all else fails.

Not sure how everything got hosed, but its got to be a change to your file sharing or permission config since you last rebuilt the VM (I don't  think it's related to this update with the Celery install.)

Good luck.  I hope your Vagrant sobers up and gets his life together!

**Comment by vsoch** [comment]
Now it freezes entirely when I try to mount NFS folders.

**Comment by vsoch** [comment]
Don't worry I'm not giving up on this.

**Comment by vsoch** [comment]
It's so beautiful.

screenshot from 2015-02-06 22 18 46

**Comment by vsoch** [comment]
Ok, a few comments. The trouble I was having I think will be resolved when NeuroVault/NeuroVault.git is the version that supports celery, or if I had changed the path in confs/nvault.pp. My first go was with a new machine, and the exportfs errors lead to corrupting my current machine, so then I was trying from the directory of my current NeuroVault repository, but given the existence of most of the directories, it seemed to be skipping over much of the install stuffs that ultimately lead to an errored installation (which was too far down the path of doom to debug).  It was when I deleted all machines entirely and started from a new directory that I had the most luck, however my mistake was not changing the version of NeuroVault to clone - because choosing the current (without celery) obviously led to error. Some comments for discussion:

  - python-redis needs to be installed in order for django/celery to be able to work. I can add this to the requirements.txt in the current NeuroVault enh/image_comparison if you agree.
  - I think that we 100% need a troubleshooting guide, especially for the early exportfs issues which I would say are bound to happen, and the only way to fix is to delete the old records in /etc/exports.  I think trouble is very likely to happen just because of differences in platforms, and we should have a guide that tells the user about how to debug, and the different options.  I have started one and can do a pull request when we finish up this testing.
  - The django-celery stuffs is done second to last before we continue django, and at the end we start both daemons.  It seems this would be very likely to trigger an error (it did for me):

        ==> default: Error: /etc/init.d/neurovault-tasks restart returned 1 instead of one of [0]

and that would completely stop the install and miss the last manifest to set up django.  If the similarity metric needs to be added anyway, is it worth getting the tasks and daemon running, because the user would have to restart all that anyway? Would we want to either move starting the daemons to the end, or create a "run_me.sh" post install script for the user to do manually [including adding the similarity metric, django makemigrations, migrate, etc.]? 

The daemon still isn't working for me (the manual start is) but I don't think it's fair to report that, because my install wasn't an error-free one.  I can test again at some point, but likely not this weekend because I want to do some work with a working dev server! :panda_face:

**Comment by guestMIBCA** [comment]
@infocortex How do you recommend going about upgrading the production server?

**Comment by chrisfilo** [comment]
@infocortex How do you recommend updating the production server?

**Comment by chrisfilo** [comment]
Thanks for showing which packages to install in the other thread. I also need to create and modify init and confing files for celery I guess? Is there some way to instruct puppet to perform those updates?

**Comment by infocortex** [comment]
> @infocortex How do you recommend updating the production server?

it should be as simple as merging the PRs (both app and puppet) and running puppet as root i.e. `puppet apply --verbose --debug /etc/puppet/modules/neurovault/confs/nvault.pp`.

I'd like to do a tiny bit more testing, and add a couple little things:
- username/password for redis- currently, redis would be dependent on a firewall to not be wide-open.
- Puppet optional flag to run the correlation data generation at deploy time as recommended by @vsoch  (optional because its quite demanding, took about 8 hours single-threaded on my MBPr).
- On a related note, wrap the `add_similarity_metric` script in Multiprocessing (or actually just use the celery queue) to parallelize it, to minimize the wait.

> is it worth getting the tasks and daemon running, because the user would have to restart all that anyway? Would we want to either move starting the daemons to the end, or create a "run_me.sh" post install script for the user to do manually [including adding the similarity metric, django makemigrations, migrate, etc.]?

Yeap, sorry about that, much more reliable to install the celery and init stuff last, I'll make that change.  The django DB setup stuff is all cooked into Puppet already, (except for the similarity metric generation as mentioned).

**Comment by chrisfilo** [comment]
On Mon, Feb 9, 2015 at 6:56 PM, Gabriel Rivera <notifications@github.com>
wrote:

> @infocortex <https://github.com/infocortex> How do you recommend updating
> the production server?
>
> it should be as simple as merging the PRs (both app and puppet) and
> running puppet as root i.e. puppet apply --verbose --debug
> /etc/puppet/modules/neurovault/confs/nvault.pp.
>
Yes this is what I was expecting, but sadly it ended up in an error. I
unfortunately did not save it thinking it was not suppose to work to begin
with. Will test again.

> I'd like to do a tiny bit more testing, and add a couple little things:
>
>    - username/password for redis- currently, redis would be dependent on
>    a firewall to not be wide-open.
>
> Extra security is always good. Could we limit redis to listen only to
localhost?

>
>    - Puppet optional flag to run the correlation data generation at
>    deploy time as recommended by @vsoch <https://github.com/vsoch>
>    (optional because its quite demanding, took about 8 hours single-threaded
>    on my MBPr).
>    - On a related note, wrap the add_similarity_metric script in
>    Multiprocessing (or actually just use the celery queue) to parallelize it,
>    to minimize the wait.
>
> I think spawning celery jobs is a better option.

>
>
>  is it worth getting the tasks and daemon running, because the user would
> have to restart all that anyway? Would we want to either move starting the
> daemons to the end, or create a "run_me.sh" post install script for the
> user to do manually [including adding the similarity metric, django
> makemigrations, migrate, etc.]?
>
> Yeap, sorry about that, much more reliable to install the celery and init
> stuff last, I'll make that change. The django DB setup stuff is all cooked
> into Puppet already, (except for the similarity metric generation as
> mentioned).
>
I'm a bit lost here, but I guess it will make sense when I see the commit.
Thanks!

**Pull request merged**
