### PR TITLE
puppet requirements for FEAT support

### PR DESCRIPTION
**Pull request by infocortex**
- [prov toolbox] (python) (https://github.com/trungdong/prov)
- [ProvToolbox (java (temporary))](https://github.com/lucmoreau/ProvToolbox)
- dev build of https://github.com/incf-nidash/nidmresults.git
- dev build of https://github.com/infocortex/nidm-results_fsl.git

### CODE REVIEW

**Comment by chrisfilo** [comment]
Could you provide instructions for adding new dependencies to already deployed server?

**Comment by infocortex** [comment]
Sure, this should cover it:

- `apt-get install default-jre unzip`
- `cd /path/to/virtualenv; source bin/activate`
- `cd lib`
- `wget -O toolbox-0.6.1-release.zip http://search.maven.org/remotecontent?filepath=org/openprovenance/prov/toolbox/0.6.1/toolbox-0.6.1-release.zip`
- `unzip toolbox-0.6.1-release.zip`
- add `/etc/profile.d/provtoolbox.shetc/profile.d/provtoolbox.sh` with the path line:  `export PATH="/path/to/venv/provToolbox/bin:$PATH"`

setup (develop mode to link git repos) the python libs:

- `git clone https://github.com/trungdong/prov.git`
- `./prov/setup.py develop`

- `git clone https://github.com/incf-nidash/nidmresults.git`
- `./nidmresults/setup.py develop`

Temp of nidmfsl branch until it's merged:

- `git clone -b nv_testdata_fixes https://github.com/infocortex/nidm-results_fsl.git`
- `./nidm-results_fsl/setup.py develop`

**Comment by infocortex** [comment]
Typos in paths above updated. -g

**Comment by infocortex** [comment]
Sorry, the .zip detection is still expecting .feat.zip, which isn't correct of course- I'll fix that now.  Won't take long.

**Pull request merged**
